eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  spring:
  cloud:
    gateway:
      routes:
        - id: discovery-server-static
          uri: http://localhost:8761

management:
  racing:
    samplind:
      probability: 1.0
