eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8085
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Akankshaanpat/microservice-tutorial-config
          clone-on-start: true
